### ISSUE TITLE
General question: Does Google have a list in Spanish?

### ISSUE THREAD

**Issue by inglesuniversal** [coffee-and-fun/google-profanity-words#11]
I am willing to contribute if required!

Thanks

PS: Where do I go to update translations from Google? I've done it in the past but can't remember the URL

Thanks

**Comment by RobertJGabriel** [comment]
Hey @inglesuniversal 

I'm just about to publish version 2 which allows you to change language.

I would love for you add any words :)

Thank you
Robert James Gabriel
