### ISSUE TITLE
Remove duplicates

### ISSUE THREAD

**Issue by dave-meyer** [coffee-and-fun/google-profanity-words#15]
Firstly, thank you for maintaining this project.

The following words occur twice in the list, which is unnecessary.
* cocksuck
* cocksucked
* cuntlick
* cuntlicker
* cuntlicking
* gangbanged
* jiz
* jizm
* orgasim
* pissin
* pissoff
* shitty

I would have removed them myself and created a merge request, but I don't want this repository to appear on my profile. 😅

Thanks!

**Comment by RobertJGabriel** [comment]
@dave-meyer 

Thank you for the issue and not many people do 😆 

I will get to this during the week

**Comment by sonyarianto** [comment]
by the way, the duplication still there, duplication cause by e.g. "shitty" and "shitty ".
