### ISSUE TITLE
Feature Request : Search the whole sentence or paragraph

### ISSUE THREAD

**Issue by nla-asia** [coffee-and-fun/google-profanity-words#17]
I am not sure how is the .search function intended to be used. Currently, it cannot be used to check a sentence whether it contains cursed words or not. Searching only one word does not help much. I think I can loop through each word and call the .search function on each one but it should be already in the package.

**Comment by RobertJGabriel** [comment]
Hey @nla-asia,

Will get this added this week :)

Will post here when its updated.

Thank you for reporting.

**Comment by RobertJGabriel** [comment]
Hey @nla-asia 

This function is now released. Just make sure you update to the latest version.

```javascript

const sentence = 'Do not use bad words like mierda or idiota.';
const hasCurseWords = profanity.hasCurseWords(sentence);
// Returns true if the sentence contains profanity words, otherwise false.

```

**Comment by nla-asia** [comment]
awesome!

**Comment by nla-asia** [comment]
awesome!
