### ISSUE TITLE
Error while importing

### ISSUE THREAD

**Issue by ManiKumarGouni-KSU** [coffee-and-fun/google-profanity-words#9]
[Could](url) not find a declaration file for module '@coffeeandfun/google-profanity-words'. ['C:/Users/Vishnu/Desktop/WS/node_modules/@coffeeandfun/google-profanity-words/index.js'](url) implicitly has an 'any' type.
  Try `npm i --save-dev @types/coffeeandfun__google-profanity-words` if it exists or add a new declaration (.d.ts) file containing `declare module '@coffeeandfun/google-profanity-words'
![Screenshot (11)](https://user-images.githubusercontent.com/99055144/156862063-27dd9dc9-4b9e-40d3-8d67-cfa549eb78eb.png)

**Comment by confused-Techie** [comment]
I know this is super late. But did you try using the dashes on the name as in:

```javascript
import { ProfanityEngine } from "@coffee-and-fun/google-profanity-words";
```

**Comment by RobertJGabriel** [comment]
Hey @ManiKumarGouni-KSU 

All fixed and updated. Just make sure you update the module.

Thank you
Robert James

**Comment by quangIle** [comment]
Hi @RobertJGabriel 

I have just installed and this error is still there

**Comment by stuartwk** [comment]
I am getting this error as well for v2.1.0.

**Comment by smwillson** [comment]
I am also getting the same error for @coffeeandfun/google-profanity-words: 2.1.0. This issue is unresolved.
